### ISSUE TITLE
graphviz-dot problem with simple example

### ISSUE THREAD

**Issue by jenisys** [mingrammer/diagrams#16] opened 2020-02-13 16:05 UTC
VERSION-INFO: diagrams 0.3.0, graphviz 0.13.2 (Python package), graphviz dot 2.43.0, Python 3.8.0, macOS

Example:
```python
# -- FILE: diagram_1.py
from diagrams import Diagram
from diagrams.aws.compute import EC2

with Diagram("Simple Diagram"):
    EC2("web")
```

```bash
$ python diagram_1.py
...
graphviz.backend.CalledProcessError: Command '['dot', '-Tjpg', '-O', 'simple_diagram']' died with <Signals.SIGILL: 4>. [stderr: b'']
```

Seems to be related to constuct `image=".../resources/aws/compute/ec2.png" ` in "simple_diagram" dot-file. If I remove this construct, I can process the dot-file just fine with `dot`.

**Comment by mingrammer** [comment] 2020-02-13 16:17
What is your macOS version? I can't reproduce it. (with the same versions for all except Graphviz dot 2.42.2)

**Comment by jenisys** [comment] 2020-02-13 20:15
Using macOS 10.14.x, graphviz was installed with brew (which normally takes care of macOS versions variances). Note that graphviz-dot is usable in principle, image=<filepath> is also OK, I can open the PNG file by using the filepath.

One correction, installed graphviz package is 2.42.2, but if you ask `dot` for its version you get `2.43.0`.

**Comment by mingrammer** [comment] 2020-02-14 00:43
Oh sorry, Yes, my `dot` version also is `2.43.0`.

Hm. .. Could you please your full `dot` code for the above diagram? I need to compare your dot code and mine.

**Comment by jenisys** [comment] 2020-02-14 17:07
As already stated, the `image=...`attribute seems to be causing the problem.

```graphviz
# -- FILE: simple_diagram
digraph "Simple Diagram" {
	graph [fontcolor="#2D3436" fontname="Sans-Serif" fontsize=15 label="Simple Diagram" nodesep=0.60 pad=2.0 rankdir=LR ranksep=0.75 splines=ortho]
	node [fixedsize=true fontcolor="#2D3436" fontname="Sans-Serif" fontsize=13 height=1.4 imagescale=true labelloc=b shape=box style=rounded width=1.4]
	edge [color="#7B8894"]
	bc91704d1167f5988d2be776b9bf2fbf [label=web height=1.9 image="/Users/xxx/diagrams_1/.venv_py3/lib/python3.8/site-packages/resources/aws/compute/ec2.png" shape=none]
}
```

**Comment by mingrammer** [comment] 2020-02-14 18:28
It's mine.

```
digraph "Simple Diagram" {
	graph [fontcolor="#2D3436" fontname="Sans-Serif" fontsize=15 label="Simple Diagram" nodesep=0.60 pad=2.0 rankdir=LR ranksep=0.75 splines=ortho]
	node [fixedsize=true fontcolor="#2D3436" fontname="Sans-Serif" fontsize=13 height=1.4 imagescale=true labelloc=b shape=box style=rounded width=1.4]
	edge [color="#7B8894"]
	"691c0a63bb283f1adf6f0e8dc4e54088" [label=web height=1.9 image="/Users/xxx/workspace/mingrammer/diagrams/resources/aws/compute/ec2.png" shape=none]
}
```

I don't understand why `image=` field causes the `SIGILL` error (illegal instruction) .. It could be an issue of `dot` installed on your system of some CPU / memory corruptions.

Could you try rebooting your computer? (maybe, can solve the corrupted memory problem..)

Reference: https://stackoverflow.com/questions/7901867/what-causes-signal-sigill

**Comment by mingrammer** [comment] 2020-02-23 11:02
Is it solved?

**Comment by jenisys** [comment] 2020-02-25 21:24
I retried it with diagrams-0.6.3, but the problem still exists (SIGILL, ILLEGAL INSTRUCTION), problem is the image=xxx attribute.

**Comment by mingrammer** [comment] 2020-02-26 02:21
Rebooting can't solve that problem? Hmm ..

**Comment by mingrammer** [comment] 2020-04-18 14:35
I close it. Reopen if same problem raises.

**Closed by mingrammer** 2020-04-18 14:36 UTC
Labels: question

**Comment by yerrochdi** [comment] 2021-03-17 11:54
conda install -c conda-forge graphviz xorg-libxrender xorg-libxpm
pip install graphviz

works for me !!!!
