### ISSUE TITLE
Unable to install from git repo

### ISSUE THREAD

**Issue by darkpixel** [mingrammer/diagrams#14] opened 2020-02-12 21:21 UTC
```
$ pip install git+https://github.com/mingrammer/diagrams.git
Collecting diagrams
  Cloning https://github.com/mingrammer/diagrams.git to /tmp/pip-install-zdyzzhwr/diagrams
  Running command git clone -q https://github.com/mingrammer/diagrams.git /tmp/pip-install-zdyzzhwr/diagrams
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: unknown, unknown
  Building wheel for unknown (PEP 517) ... done
  Created wheel for unknown: filename=UNKNOWN-0.0.0-py3-none-any.whl size=1793 sha256=93f4e178ba3c2f880603d05c884d9d14d3d322f5608ec62b1d2eb39e62ab4f1e
  Stored in directory: /tmp/pip-ephem-wheel-cache-eg2nh1lt/wheels/c7/24/85/a8af6e1f27e0c24832c17821bdb6065697ff028f31e6a6ac5d
  Building wheel for unknown (PEP 517) ... done
  Created wheel for unknown: filename=UNKNOWN-0.0.0-py3-none-any.whl size=1793 sha256=93f4e178ba3c2f880603d05c884d9d14d3d322f5608ec62b1d2eb39e62ab4f1e
  Stored in directory: /tmp/pip-ephem-wheel-cache-eg2nh1lt/wheels/a3/19/3f/ef83c6a207c0f5f7acbc4a25c53aa54d690ac4dd6b201ccd1e
Successfully built unknown unknown
pInstalling collected packages: unknown
Successfully installed unknown-0.0.0
$ pip freeze
graphviz==0.13.2
Jinja2==2.11.1
MarkupSafe==1.1.1
UNKNOWN==0.0.0
$
```
It installs as 'UNKNOWN==0.0.0' instead of diagrams.

**Comment by mingrammer** [comment] 2020-02-13 03:07
Why not use just ”pip install diagrams”? Any reason?

**Comment by mingrammer** [comment] 2020-02-13 03:13
It seems to be caused by not uploading the .whl files created by poetry to this repository.

**Comment by darkpixel** [comment] 2020-02-13 04:39
@mingrammer I figured #12 might be fixed in the repo already.  It wasn't.  Then I realized it was simply a matter of pip installing contextvars.  Plus some people like to test against master. ;)

**Comment by mingrammer** [comment] 2020-02-13 14:49
@darkpixel diagrams v0.2.4 releases! You can `pip install diagrams` on Python 3.6 env.

\+ and "install from git repo" would be good to someone, but it is not a big issue now I think. I'll consider this feature when more people want it ;)

**Comment by mingrammer** [comment] 2020-02-23 10:52
I close this issue. Reopen it later if needed. Thanks.

**Closed by mingrammer** 2020-02-23 10:52 UTC
